### PR TITLE
Md3 addition

### PR DESCRIPTION
**Pull request by ScottEllisNovatex**
First pull request...

### CODE REVIEW

**Comment by neilstephens** [comment]
Give me a call to discuss if you like. This Github review process is new to me too, so we can figure it out together!

**Comment by neilstephens** [comment]
And I meant to say, WOW, you've done heaps in a short time. Looking forward to merging in and having a closer look.

Neil.

**Comment by neilstephens** [comment]
I ended up merging into a feature branch. There were other changes I had to make to get things building under Linux, and so I could execute tests without visual studio, so I recommend you pull those changes back into your fork.

**Comment by ScottEllisNovatex** [comment]
I was looking at it yesterday, the catch version I used was a
      special one that allowed the Test framework to find the tests.
    I will pull the changes back. Still getting the hang of things.
    Spent some time using Microsoft Message Analyser to take the big
      packet capture and bring it down to only the MD3 messages. I used
      a filter that the message length was always mod 6, last byte of
      each 6 is zero and first byte of first message could not be zero
      and it was pretty accurate.
    Started looking at the lua wireshark filter, so I can generate
      good function stats into excel.
    Scott
    
    
    On 14/04/2018 1:44 PM, Neil Stephens
      wrote:
    
    
      I ended up merging into a feature branch. There were other
        changes I had to make to get things building under Linux, and so
        I could execute tests without visual studio, so I recommend you
        pull those changes back into your fork.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/neilstephens/opendatacon","title":"neilstephens/opendatacon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/neilstephens/opendatacon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@neilstephens in #41: I ended up merging into a feature branch. There were other changes I had to make to get things building under Linux, and so I could execute tests without visual studio, so I recommend you pull those changes back into your fork. "}],"action":{"name":"View Pull Request","url":"https://github.com/neilstephens/opendatacon/pull/41#issuecomment-381300787"}}}
    
    
    -- 
      Scott Ellis
        
          Principal
        
        Novatex Research - Excellence in Electronic Research &
        Development
        41 Yule Road, Merewether, Newcastle, NSW 2291, Australia
        Phone: 0412 988408

**Comment by neilstephens** [comment]
I still used catchvs.hpp for your stuff, I just added an entry point to
call the tests from an exe. It should still work with the visual studio
hooks.

Neil.

**Comment by ScottEllisNovatex** [comment]
Merged your changes, did some of the other tidy up you mentioned.

**Pull request merged**
